server:
  port: 8086

spring:
  application:
    name: api-gateway

  cloud:
    gateway:


      routes:
        - id: user-login
          uri: http://user-microservices:8081
          predicates:
            - Path=/api/usuarios/**

        - id: notification-microservice-notificacion
          uri: http://notification-microservices:8085
          predicates:
            - Path=/api/notificaciones/**

        - id: estudiante-microservice
          uri: http://estudiante-microservices:8084
          predicates:
            - Path=/api/estudiante/**

        - id: empresa-microservice-empresas
          uri: http://empresa-microservices:8082
          predicates:
            - Path=/api/empresas/**

        - id: coordinador-microservice
          uri: http://coordinador-microservices:8083
          predicates:
            - Path=/api/coordinador/**

        - id: empresa-microservice-proyectos
          uri: http://empresa-microservices:8082
          predicates:
            - Path=/api/proyectos/**

        - id: notification-microservice-comentarios
          uri: http://notification-microservices:8085
          predicates:
            - Path=/api/comentarios/**

        - id: empresas-microservice
          uri: http://empresa-microservices:8082
          predicates:
            - Path=/api/comentariosEmpresa/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ManageSoft

# Opcional logueo para debug
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
    co.edu.unicauca.apigateway: TRACE
    org.springframework.web.filter: DEBUG
    org.springframework.security.web.csrf: DEBUG
